### ISSUE TITLE
Update Dependencies with last version of PyMS and other libs

### ISSUE THREAD

**Issue by avara1986** [python-microservices/cookiecutter-pyms#7]
Update Pipfile and requirements.txt with last versions of the libraries like the [Microservices Scaffold](https://github.com/python-microservices/microservices-scaffold)

**Comment by iamlordutkarsh** [comment]
I want to work on this , can u assign me this ?

**Comment by avara1986** [comment]
Thank you @iamlordutkarsh ! ^^ Don't forget to register in https://hacktoberfest.digitalocean.com/ :+1:

**Comment by iamlordutkarsh** [comment]
Thanks @avara1986 I registered
